### PR TITLE
Fixed comment typos

### PR DESCRIPTION
**Pull request by WRFitch**
This PR fixes two typos in the comments in src/charm.py. 

Apologies if this seems nitpicky; it's required for an onboarding task.

### CODE REVIEW

**Comment by WRFitch** [comment]
I have signed the ubuntu code of conduct and I've now linked my github and [launchpad](https://launchpad.net/~wrfitch) accounts, so if it were to run again the failing CI check should pass. I can commit again but I don't want to create unnecessary commits.

**Comment by simondeziel** [comment]
@WRFitch thanks for the contribution!

The CLA check is still failing which could be because of 2 things (not too sure which): your LP account doesn't list any email and your commits are not "signed-off" (`git commit -s`).

**Comment by stgraber** [comment]
Unless you've also signed the Canonical CLA personally with your private address you need to make sure the commit author address uses your work address so the CLA check clears you as a Canonical employee.

Something like this should do it:
 - `git commit --amend --author="Will Fitch <will.fitch@canonical.com>"`
 -  git push --force

**Comment by WRFitch** [comment]
Amending the commit with my canonical email address worked - thanks for the help :)

**Pull request merged**
